# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SMrqwyCEx4s1m2kOr0GEGW7rd5KpzGnz
"""

import numpy as np
from datetime import datetime, timedelta  # FIX 1: Added timedelta import
import string


def run_groupdna_analysis(file_path):
    # ==========================================
    # FEATURE 1: THE CHAT PARSER
    # ==========================================
    messages = []
    sys_msg_count = 0
    media_count = 0
    deleted_count = 0

    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            lines = f.readlines()
    except FileNotFoundError:
        print("Error: Could not find the file. Please ensure 'hostel_bois.txt' is uploaded.")
        return

    for line in lines:
        line = line.strip()
        if not line:
            continue

        parts = line.split(" - ", 1)
        if len(parts) < 2:
            continue

        timestamp_str = parts[0]
        content_str = parts[1]

        sender_parts = content_str.split(": ", 1)
        if len(sender_parts) < 2:
            sys_msg_count += 1
            continue

        sender = sender_parts[0]
        text = sender_parts[1]

        if text == "<Media omitted>":
            media_count += 1
            is_media = True
            is_deleted = False
        elif text == "This message was deleted":
            deleted_count += 1
            is_deleted = True
            is_media = False
        else:
            is_media = False
            is_deleted = False

        try:
            dt_obj = datetime.strptime(timestamp_str, '%d/%m/%y, %H:%M')
        except ValueError:
            continue

        messages.append({
            'timestamp': dt_obj,
            'sender': sender,
            'text': text,
            'is_media': is_media,
            'is_deleted': is_deleted
        })

    if not messages:
        print("No messages parsed. Check the file format.")
        return

    # ==========================================
    # FEATURE 2: GROUP OVERVIEW
    # ==========================================
    total_messages = len(messages)
    first_date = messages[0]['timestamp']
    last_date = messages[-1]['timestamp']
    total_days = (last_date - first_date).days + 1

    person_counts = {}
    unique_dates = set()

    for msg in messages:
        sender = msg['sender']
        person_counts[sender] = person_counts.get(sender, 0) + 1
        unique_dates.add(msg['timestamp'].date())

    participants = list(person_counts.keys())
    total_participants = len(participants)

    sorted_counts = sorted(person_counts.items(), key=lambda x: x[1], reverse=True)

    # ==========================================
    # FEATURE 3: MOST ACTIVE DAY AND HOUR
    # ==========================================
    date_counts = {}
    hour_counts = {}

    for msg in messages:
        d = msg['timestamp'].date()
        h = msg['timestamp'].hour
        date_counts[d] = date_counts.get(d, 0) + 1
        hour_counts[h] = hour_counts.get(h, 0) + 1

    busiest_day = max(date_counts.items(), key=lambda x: x[1])
    busiest_hour = max(hour_counts.items(), key=lambda x: x[1])

    # ==========================================
    # FEATURE 4: ACTIVITY HEATMAP (NumPy)
    # ==========================================
    p_to_idx = {p: i for i, p in enumerate(participants)}

    heatmap_matrix = np.zeros((total_participants, 24), dtype=int)

    for msg in messages:
        r = p_to_idx[msg['sender']]
        c = msg['timestamp'].hour
        heatmap_matrix[r, c] += 1

    # ==========================================
    # FEATURE 5: TOP WORDS
    # ==========================================
    stop_words = {
        'i', 'is', 'the', 'a', 'and', 'or', 'to', 'of', 'in', 'on',
        'for', 'this', 'was', 'so', 'my', 'me', 'it', 'with', 'but',
        'we', 'how', 'that', 'are', 'you', 'what'
    }
    word_counts = {}

    for msg in messages:
        if msg['is_media'] or msg['is_deleted']:
            continue

        clean_text = msg['text'].lower()
        for p in string.punctuation:
            clean_text = clean_text.replace(p, '')

        words = clean_text.split()
        for w in words:
            if w not in stop_words and len(w) > 2:
                word_counts[w] = word_counts.get(w, 0) + 1

    top_10_words = sorted(word_counts.items(), key=lambda x: x[1], reverse=True)[:10]

    # ==========================================
    # FEATURE 6: RESPONSE SPEED & SILENT STREAKS
    # ==========================================
    response_times = {p: [] for p in participants}
    daily_activity = {p: set() for p in participants}

    last_sender = None
    last_time = None

    for msg in messages:
        sender = msg['sender']
        dt = msg['timestamp']

        daily_activity[sender].add(dt.date())

        if last_sender is not None and last_sender != sender:
            gap = (dt - last_time).total_seconds()
            if gap < 86400:
                response_times[sender].append(gap)

        last_sender = sender
        last_time = dt

    avg_responses = {}
    for p, times in response_times.items():
        if times:
            avg_responses[p] = sum(times) / len(times)
        else:
            avg_responses[p] = 0

    # FIX 4: Guard against empty list when all response times are 0
    positive_responders = [(p, t) for p, t in avg_responses.items() if t > 0]
    if positive_responders:
        fastest_replier = min(positive_responders, key=lambda x: x[1])
        slowest_replier = max(avg_responses.items(), key=lambda x: x[1])
    else:
        fastest_replier = ("N/A", 0)
        slowest_replier = ("N/A", 0)

    # Silent Streaks Logic
    longest_streaks = {}
    all_dates = [first_date.date() + timedelta(days=i) for i in range(total_days)]

    for p in participants:
        max_streak = 0
        current_streak = 0
        for d in all_dates:
            if d not in daily_activity[p]:
                current_streak += 1
                if current_streak > max_streak:
                    max_streak = current_streak
            else:
                current_streak = 0
        longest_streaks[p] = max_streak

    sorted_streaks = sorted(longest_streaks.items(), key=lambda x: x[1], reverse=True)

    # ==========================================
    # FEATURE 7: PERSONALITY ARCHETYPES
    # ==========================================

    # FIX 2 & 3: score_spammer now works purely on the given message list (per-person)
    def score_spammer(msgs):
        if not msgs:
            return 0
        bursts = []
        current_burst = 1
        for i in range(1, len(msgs)):
            if msgs[i]['sender'] == msgs[i - 1]['sender']:
                current_burst += 1
            else:
                if current_burst > 1:
                    bursts.append(current_burst)
                current_burst = 1
        # Catch the last burst
        if current_burst > 1:
            bursts.append(current_burst)
        return sum(bursts) / len(bursts) if bursts else 0

    def score_mom(msgs):
        caring_words = ['okay', 'safe', 'eat', 'sleep', 'take care', 'are you',
                        'please', 'reminder', 'drink water', 'forget']
        score = 0
        for m in msgs:
            if m['is_media'] or m['is_deleted']:
                continue
            text = m['text'].lower()
            if any(cw in text for cw in caring_words):
                score += 1
        return score

    def score_night_owl(p_idx, matrix):
        total = np.sum(matrix[p_idx])
        if total == 0:
            return 0
        night_msgs = matrix[p_idx, 23] + np.sum(matrix[p_idx, 0:5])
        return (night_msgs / total) * 100

    def score_storyteller(msgs):
        word_counts_local = [
            len(m['text'].split()) for m in msgs
            if not m['is_media'] and not m['is_deleted']
        ]
        return sum(word_counts_local) / len(word_counts_local) if word_counts_local else 0

    def score_drama_queen(msgs):
        drama_count = 0
        valid_msgs = [m for m in msgs if not m['is_media'] and not m['is_deleted']]
        for m in valid_msgs:
            text = m['text']
            if (text.isupper() and len(text) >= 3) or text.count('!') >= 2:
                drama_count += 1
        return (drama_count / len(valid_msgs) * 100) if valid_msgs else 0

    def score_ghost(p):
        absent_days = total_days - len(daily_activity[p])
        return (absent_days / total_days) * 100

    def score_lazy_texter(msgs):
        word_counts_local = [
            len(m['text'].split()) for m in msgs
            if not m['is_media'] and not m['is_deleted']
        ]
        avg_words = sum(word_counts_local) / len(word_counts_local) if word_counts_local else 999
        return max(0, 10 - avg_words)

    archetype_scores = {p: {} for p in participants}

    for p in participants:
        p_msgs = [m for m in messages if m['sender'] == p]
        p_idx = p_to_idx[p]

        # FIX 2: Pass only this person's messages to score_spammer
        archetype_scores[p]['THE SPAMMER'] = score_spammer(p_msgs)
        archetype_scores[p]['THE GROUP MOM'] = score_mom(p_msgs)
        archetype_scores[p]['THE NIGHT OWL'] = score_night_owl(p_idx, heatmap_matrix)
        archetype_scores[p]['THE STORYTELLER'] = score_storyteller(p_msgs)
        archetype_scores[p]['THE DRAMA QUEEN'] = score_drama_queen(p_msgs)
        archetype_scores[p]['THE GHOST'] = score_ghost(p)
        archetype_scores[p]['THE LAZY TEXTER'] = score_lazy_texter(p_msgs)

    assigned_archetypes = {}
    available_archetypes = [
        'THE SPAMMER', 'THE GROUP MOM', 'THE NIGHT OWL',
        'THE STORYTELLER', 'THE DRAMA QUEEN', 'THE GHOST', 'THE LAZY TEXTER'
    ]

    while len(assigned_archetypes) < len(participants) and available_archetypes:
        best_p, best_arch, best_score = None, None, -1

        for p in participants:
            if p in assigned_archetypes:
                continue
            for arch in available_archetypes:
                if archetype_scores[p][arch] > best_score:
                    best_score = archetype_scores[p][arch]
                    best_p = p
                    best_arch = arch

        # FIX 7: Guard against infinite loop if no best found
        if best_p is None:
            break

        assigned_archetypes[best_p] = (best_arch, best_score)
        available_archetypes.remove(best_arch)

    # ==========================================
    # FEATURE 8: THE FINAL REPORT (Formatting)
    # ==========================================
    print("=" * 60)
    print(f"{'GROUPDNA REPORT':^60}")
    print("=" * 60)
    print(f"Group          : WhatsApp Chat Analysis")
    print(f"Period         : {first_date.strftime('%d %B %Y')} to {last_date.strftime('%d %B %Y')} ({total_days} days)")
    print(f"Total messages : {total_messages:,} messages")
    print(f"Participants   : {total_participants} members")
    print("-" * 60)
    print(f"Busiest day    : {busiest_day[0].strftime('%d %B %Y')} ({busiest_day[1]} messages)")
    print(f"Busiest hour   : {busiest_hour[0]:02d}:00 - {busiest_hour[0] + 1:02d}:00")

    print("\n" + "=" * 60)
    print("MESSAGES PER PERSON")
    print("-" * 60)
    for p, count in sorted_counts:
        pct = (count / total_messages) * 100
        print(f"{p:<12} : {count:>5} ({pct:>4.1f}%)")

    print("\n" + "=" * 60)
    print("ACTIVITY HEATMAP (messages by hour)")
    print("-" * 60)
    print(f"{'':<10} 00 03 06 09 12 15 18 21")
    for p in participants:
        row = heatmap_matrix[p_to_idx[p]]
        max_val = np.max(row) if np.max(row) > 0 else 1
        blocks = []
        for h in [0, 3, 6, 9, 12, 15, 18, 21]:
            val = row[h]
            pct = val / max_val
            if pct == 0:
                char = '.'
            elif pct <= 0.25:
                char = '░'
            elif pct <= 0.50:
                char = '▒'
            elif pct <= 0.75:
                char = '▓'
            else:
                char = '█'
            blocks.append(char)
        print(f"{p:<10} {'  '.join(blocks)}")

    print("\n" + "=" * 60)
    print("THIS GROUP'S FAVOURITE WORDS")
    print("-" * 60)
    max_word_count = top_10_words[0][1] if top_10_words else 1
    for word, count in top_10_words:
        bar_len = int((count / max_word_count) * 20)
        bar = "█" * bar_len
        print(f"{word:<12} {count:>4} | {bar}")

    print("\n" + "=" * 60)
    print("RESPONSE PATTERNS")
    print("-" * 60)
    print(f"Fastest replier: {fastest_replier[0]:<8} (avg {fastest_replier[1] / 60:.1f} minutes)")
    print(f"Slowest replier: {slowest_replier[0]:<8} (avg {slowest_replier[1] / 3600:.1f} hours)")

    print("\nLONGEST SILENT STREAKS")
    for p, streak in sorted_streaks:
        if streak > 0:
            print(f"{p:<12} : {streak} days")
        else:
            print(f"{p:<12} : 0 days (never went silent)")

    print("\n" + "=" * 60)
    print("PERSONALITY ARCHETYPES")
    print("-" * 60)
    for p, (arch, score) in assigned_archetypes.items():
        if arch == 'THE SPAMMER':
            metric = f"(avg {score:.1f} msgs in a row)"
        elif arch == 'THE GROUP MOM':
            metric = f"(caring keyword score: {score})"
        elif arch == 'THE NIGHT OWL':
            metric = f"({score:.1f}% msgs between 23h-04h)"
        elif arch == 'THE STORYTELLER':
            metric = f"(avg {score:.1f} words per msg)"
        elif arch == 'THE DRAMA QUEEN':
            metric = f"({score:.1f}% ALL-CAPS messages)"
        elif arch == 'THE GHOST':
            metric = f"(silent on {score:.1f}% of days)"
        elif arch == 'THE LAZY TEXTER':
            metric = f"(lowest avg words per msg)"
        else:
            metric = f"(score: {score:.1f})"

        print(f"{p:<10} -> {arch:<18} {metric}")

    print("=" * 60)
    print(f"{'Generated by GroupDNA':^60}")
    print(f"{'Built with Python + NumPy':^60}")
    print("=" * 60)


# Run the project
run_groupdna_analysis('hostel_bois.txt')